+incdir+/home/liuyunqi/tree/pcpp/qwerwr
+incdir+./qwer
-y2333.v
-y/home/liuyunqi/tree/pcpp/fexpand
/home/liuyunqi/tree/pcpp/fexpand
/home/liuyunqi/tree/pcpp/fexpand_test/fexpand
/home/liuyunqi/tree/pcpp/open_sub1.v
/home/liuyunqi/tree/pcpp/sub1.v
/home/liuyunqi/tree/pcpp/sub2.v
../res.v
QWER/res-res.v
QWER/res-res.v
QWER/res-res.v
QWER/res-res.v
QWER/res-res.v
QWER/res-res.v
QWER/res-res.v
123.v
QWER/res-res.vqwer.v
AAAAAAAAAAAAAAAAAAAAAAAA
