#!/usr/bin/env python
from pcpp import preprocessor, PathRecord

import argparse
import sys, os




parser = argparse.ArgumentParser(prog='fexpand',
            description=
    '''A pure Python based Filelist preprocessor implementation 
    very useful for pre-preprocessing hierarchical fielist into single 
    filelist without "-f" index, macros, environment variables and comments.''',
            epilog=
    '''Note that fexpand expands all environment variables that are present 
    (those that are not present are left in place). 
    Similarly, all paths are converted to absolute paths 
    (non-existing files are left as they are). Fexpand supports most of the c99 macro syntax.
    
    (FEXPAND VERSION 1.3)''')
parser.add_argument('-i', '--input', help='input filelist path', required=True)
parser.add_argument('-o', '--output', help='output expanded filelist path', default='expanded_filelist.f')
parser.add_argument('-D', dest = 'defines', metavar = 'macro[=val]', nargs = 1, action = 'append', help = 'Predefine name as a macro [with value]',default=[])
#parser.add_argument('-h', '--help', action='help', help='show this help message and exit')

args = parser.parse_args()

print(f'[FEXPAND] Start:')
print(f'[FEXPAND] Input  file path: {args.input}')
print(f'[FEXPAND] Output file path: {args.output}')


defines = [x[0] for x in args.defines]
print(f'[FEXPAND] Marco defined in cmd line: {defines}')
#fi_path = sys.argv[1]
#fo_path = sys.argv[2]

#print(fi_path)
#print(fo_path)


fi = open(args.input,'r')
fo = open(args.output,'w')

din = fi.read()

PathRecord.CURRENT_FILE = os.path.abspath(args.input)
p = preprocessor.Preprocessor()

for d in defines:
    if '=' not in d:
        d += '=1'
    d = d.replace('=', ' ', 1)
    p.define(d)

p.parse(din)
res = p.analyze()


fo.write(res)
